python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric manhattan -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric euclidean -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric chebyshev -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric minkowski -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric canberra -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric braycurtis -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric haversine -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric mahalanobis -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric wminkowski -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric seuclidean -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric cosine -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric correlation -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric hamming -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric jaccard -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric dice -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric russellrao -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric kulsinski -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric rogerstanimoto -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric sokalmichener -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric sokalsneath -e 500 -k 10
python3 __main__.py -r data -i metahitIBD --transpose n -c 2 -t umap --colormap gray --type_bin spb --perlexity_neighbor 100 --umap_metric yule -e 500 -k 10

